[package]
name = "seymour-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
schemars = { version = "0.8", features = ["derive"] }
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"

[dev-dependencies]
pretty_assertions = "1"
